### ISSUE TITLE
Viewability causes ads to only render when scrolling is completely stopped

### ISSUE THREAD

**Issue by wfsmith** [nfl/react-gpt#44]
Reproduce:  Slowly scroll a page with a `react-gpt` ad component on it but do not stop scrolling.  You can scroll back and forth with the ad component 100% viewable but it will not render until scrolling is stopped completely.  

I am curious to know if this is a bug or a feature.  The [IAB viewability guidlines](https://www.iab.com/guidelines/state-of-viewability-transaction-2015/) state that the ad should be viewable for 1 second on mobile and 2 seconds on desktop.

**Comment by potench** [comment]
Sounds like a bug, it should anticipate viewability in order for the ad to be loaded in time

**Comment by potench** [comment]
It's being `debounced` on a 66 ms timeout without immediately executing. 
https://github.com/nfl/react-gpt/blob/f73958e7e3c88931b4e14c4e6a8ded80d2fba31f/src/createManager.js#L134-L141
We want to capture scroll data to determine if the ad is going to be viewable, we should throttle that calculation to maybe 20 or 40 ms instead of debouncing until scrolling rests. 

Will submit a PR and test this out.
