### ISSUE TITLE
request http://www.googletagservices.com/tag/js/gpt.js

### ISSUE THREAD

**Issue by ldfloresgon** [nfl/react-gpt#77]
Hello, the request "http://www.googletagservices.com/tag/js/gpt.js",
can be by SSL?

Thanks

**Comment by potench** [comment]
The seedFile is loaded from a relative protocol https://github.com/nfl/react-gpt/blob/master/src/Bling.js
I suppose we could force it to be https or allow an override, or you can host your site securely.

**Comment by ldfloresgon** [comment]
thanks @potench XD

**Comment by ldfloresgon** [comment]
what do you think about this implementation?
thanks
![image](https://user-images.githubusercontent.com/10603347/37927143-8b8076ba-3139-11e8-9391-66e6a591663f.png)

**Comment by potench** [comment]
I dunno, does it work for you? What kind of feedback are you looking for exactly?
1. `googletag` might not exist in `componentDidMount` yet
2. all those `lets` can be `consts` 
3. Look at this https://github.com/nfl/react-gpt/blob/8278236156b11ba35619bede3e32219d4c24f41b/src/Bling.js#L457-L470 to get some inspiration for managing viewability and seems like GPT takes care of the first ad render? 
4. You should provide a width/height to the <div> so your site doesn't shift as the ad renders. 

I'm gonna close this issue since it's something that might be better off posted in Stackoverflow.
